### ISSUE TITLE
Cannot connect poddit.app

### ISSUE THREAD

**Issue by michielbdejong** [pdsinterop/solid-nextcloud#132]
I just ran into this possibly related one:
* using https://github.com/pondersource/dev-stock
* `./scripts/init-solid.sh`
* `./scripts/testing-solid.sh`
* Go inside http://localhost:5800
* Visit https://nc1.docker
* Login einstein/relativity
* Inside the Nextcloud GUI, go to the Solid app (cog icon in menu on the top left)
* Try to open https://poddit.app from there

This fails silently when you select https://nc1.docker as your IDP because:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://nc1.docker/.well-known/openid-configuration. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

Error logging in with WebID-OIDC
```

**Comment by ylebre** [comment]
Release 0.8.1 adds a lot of backwards compatibility for Solid apps - if all is well this should include Poddit.app!
