### ISSUE TITLE
Deep Integration: Contacts

### ISSUE THREAD

**Issue by michielbdejong** [pdsinterop/solid-nextcloud#22]
I'm reverse engineering https://github.com/nextcloud/contacts, found something that might be useful:
```php
$coma = new ContactsManager($this->davBackend, $this->l10n);

**Comment by michielbdejong** [comment]
What I don't understand is that
appinfo/info.xml refers to
lib/Cron/SocialUpdateRegistration.php refers to
lib/Cron/SocialUpdate.php which then magically gets constructed with
```php
__construct(SocialApiService $social, IJobList $jobList)
```
How did the cronjob system know how to construct a SocialApiService to pass it to the update job? Some DI system config file I'm missing here?

**Comment by ylebre** [comment]
Contacts integration part of https://github.com/pdsinterop/solid-nextcloud/pull/40
