### ISSUE TITLE
App launcher UI

### ISSUE THREAD

**Issue by ylebre** [pdsinterop/solid-nextcloud#37]
![image](https://user-images.githubusercontent.com/10849937/109032331-d3dc5800-76c5-11eb-9918-666d3d8ee389.png)
![image](https://user-images.githubusercontent.com/10849937/109032369-e060b080-76c5-11eb-87fc-f59ea8886bc2.png)

Maybe we can use this as the replacement for the 'main' solid page in Nextcloud when we have a nice set of apps.

**Comment by michielbdejong** [comment]
Great! And so when you click 'Allow and Launch' it edits the ACLs as necessary and launches the app in question?

That means we completed [milestone 4a](https://github.com/pdsinterop/project-admin/blob/master/milestones.md#4a-solid-app-launcher) \o/

**Comment by ylebre** [comment]
Yep, acls are changed using the solid-acl-parser.  For type indexes we use the solid-typeindex-parser module.
