### ISSUE TITLE
How to use this app?

### ISSUE THREAD

**Issue by xplosionmind** [pdsinterop/solid-nextcloud#52]
I am sorry for the dumb question, but I am a non-developer with very limited technical skills. I host [my own Nextcloud instance](https://cloud.tommi.space 'Tommi’s personal cloud') and I have installed this plugin. Now what? If I try to log into Solid apps such as [Media Kraken](https://noeldemartin.github.io/media-kraken/login 'Media Kraken login page'), both `https://cloud.tommi.space` and `https://cloud.tommi.space/index.php/apps/solid/openid` do not seem to be working. Which URL should I use? Do I need to do something else after installing the app?

Sorry for the silly question, thanks a lot in advance!

**Comment by Potherca** [comment]
Hi @xplosionmind!

Thank you for opening this issue. First of: your question is totally valid. Nothing dumb/silly about it!

We're still a bit behind in documenting how this plugin works (and how to work _with_ it).

I'm currently in the process of updating various parts of the components this project is built upon, including better docs. Actual updates to this repo are not planned until December, but I can give you some instructions before then via this ticket (so you don't have to wait _too_ long.

I'll have to gather my notes together a bit before I can respond, but you should hear back from me in the coming week.

Please bear with us! :pray:

**Comment by almereyda** [comment]
There is a chance #49 already contains helpful clues about what to do next after installing.

**Comment by michielbdejong** [comment]
Also https://github.com/pdsinterop/solid-nextcloud/blob/main/INSTALL.md but it's not complete yet

**Comment by Potherca** [comment]
Things have been moving forward again lately!

Since release `v0.5.0`, when pointing a Solid app to `https://{your-nextcloud-domain}/apps/solid/@{you-user-name}/profile/card#me` things should "just work":tm:) so I am closing this issue for now.

Once #107 has been resolved, the installation should be smooth again (so you might want to wait for `v0.7.1` to be released).
