### ISSUE TITLE
Find a way to enable CORS headers

### ISSUE THREAD

**Issue by michielbdejong** [pdsinterop/solid-nextcloud#57]

**Comment by michielbdejong** [comment]
https://github.com/pdsinterop/solid-nextcloud#manual-install instructs the user to enable CORS headers on the entire server, which is overkill and *DANGEROUS* because it could allow cross-site scripting to other Nextcloud apps if the user is logged in with a cookie.

**Comment by michielbdejong** [comment]
should work with a directory tag, too:
```
<Directory /var/www/html>
   ...
   Header set Access-Control-Allow-Origin "*"
   ...
</Directory>
```

**Comment by michielbdejong** [comment]
Putting it in the Directory works for /var/www/html but not if you put it in /var/www/apps/solid because according to apache all requests are handled by /var/www/html/index.php.

**Comment by michielbdejong** [comment]
Maybe we should uncomment https://github.com/pdsinterop/php-solid-crud/blob/b6816c0/src/Server.php#L117-L123
So then at least all the routes on the storage would get CORS headers and then we would only need to deal with /.well-known/openid-provider separately.

**Comment by michielbdejong** [comment]
Ah, using that ^ and in addition, if you create a static file:
```sh
mkdir -p /var/www/html/.well-known
curl -i https://cloud.pondersource.org/index.php/apps/solid/openid > /var/www/html/.well-known/openid-configuration
```
Add this to your /etc/apache2/sites-enabled/000-default.conf:
```
<Directory /var/www/html/.well-known/>
    Header always set Access-Control-Allow-Origin: *
</Directory>
```
and then:
```sh
a2dismod rewrite
systemctl restart apache
```
Then it works! :)

**Comment by michielbdejong** [comment]
Testing this out now... next error:
```
Access to fetch at 'https://cloud.pondersource.org/index.php/apps/solid/jwks' from origin 'https://noeldemartin.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
So that needs the same edit in https://github.com/pdsinterop/php-solid-auth/blob/b08a3910d49535afd3d77db264badcd564f31f6e/src/Server.php#L148

**Comment by michielbdejong** [comment]
Fixed in https://github.com/pdsinterop/solid-nextcloud/pull/93

**Comment by Potherca** [comment]
@michielbdejong Can we close this issue?

**Comment by michielbdejong** [comment]
@Potherca it will be closed automatically when https://github.com/pdsinterop/solid-nextcloud/pull/93 is merged

**Comment by michielbdejong** [comment]
Ah, actually that wasn't true when I wrote it but it is true now :)
